# Generated by cucumber-sinatra. (2015-05-22 11:54:40 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/growler.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Growler

class GrowlerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GrowlerWorld.new
end
